/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemosIndexRouteImport } from './routes/memos/index'
import { Route as MemosCreateRouteImport } from './routes/memos/create'
import { Route as MemosMemoIdRouteImport } from './routes/memos/$memoId'
import { Route as ApiMemosRouteImport } from './routes/api/memos'
import { Route as ApiMemosIdRouteImport } from './routes/api/memos.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosIndexRoute = MemosIndexRouteImport.update({
  id: '/memos/',
  path: '/memos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosCreateRoute = MemosCreateRouteImport.update({
  id: '/memos/create',
  path: '/memos/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosMemoIdRoute = MemosMemoIdRouteImport.update({
  id: '/memos/$memoId',
  path: '/memos/$memoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemosRoute = ApiMemosRouteImport.update({
  id: '/api/memos',
  path: '/api/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemosIdRoute = ApiMemosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMemosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/upload': typeof UploadRoute
  '/api/memos': typeof ApiMemosRouteWithChildren
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/memos/create': typeof MemosCreateRoute
  '/memos': typeof MemosIndexRoute
  '/api/memos/$id': typeof ApiMemosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/upload': typeof UploadRoute
  '/api/memos': typeof ApiMemosRouteWithChildren
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/memos/create': typeof MemosCreateRoute
  '/memos': typeof MemosIndexRoute
  '/api/memos/$id': typeof ApiMemosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/upload': typeof UploadRoute
  '/api/memos': typeof ApiMemosRouteWithChildren
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/memos/create': typeof MemosCreateRoute
  '/memos/': typeof MemosIndexRoute
  '/api/memos/$id': typeof ApiMemosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches'
    | '/upload'
    | '/api/memos'
    | '/memos/$memoId'
    | '/memos/create'
    | '/memos'
    | '/api/memos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches'
    | '/upload'
    | '/api/memos'
    | '/memos/$memoId'
    | '/memos/create'
    | '/memos'
    | '/api/memos/$id'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/upload'
    | '/api/memos'
    | '/memos/$memoId'
    | '/memos/create'
    | '/memos/'
    | '/api/memos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  UploadRoute: typeof UploadRoute
  ApiMemosRoute: typeof ApiMemosRouteWithChildren
  MemosMemoIdRoute: typeof MemosMemoIdRoute
  MemosCreateRoute: typeof MemosCreateRoute
  MemosIndexRoute: typeof MemosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/': {
      id: '/memos/'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/create': {
      id: '/memos/create'
      path: '/memos/create'
      fullPath: '/memos/create'
      preLoaderRoute: typeof MemosCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/$memoId': {
      id: '/memos/$memoId'
      path: '/memos/$memoId'
      fullPath: '/memos/$memoId'
      preLoaderRoute: typeof MemosMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memos': {
      id: '/api/memos'
      path: '/api/memos'
      fullPath: '/api/memos'
      preLoaderRoute: typeof ApiMemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memos/$id': {
      id: '/api/memos/$id'
      path: '/$id'
      fullPath: '/api/memos/$id'
      preLoaderRoute: typeof ApiMemosIdRouteImport
      parentRoute: typeof ApiMemosRoute
    }
  }
}

interface ApiMemosRouteChildren {
  ApiMemosIdRoute: typeof ApiMemosIdRoute
}

const ApiMemosRouteChildren: ApiMemosRouteChildren = {
  ApiMemosIdRoute: ApiMemosIdRoute,
}

const ApiMemosRouteWithChildren = ApiMemosRoute._addFileChildren(
  ApiMemosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  UploadRoute: UploadRoute,
  ApiMemosRoute: ApiMemosRouteWithChildren,
  MemosMemoIdRoute: MemosMemoIdRoute,
  MemosCreateRoute: MemosCreateRoute,
  MemosIndexRoute: MemosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
