/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _authedRouteImport } from './routes/__authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemosIndexRouteImport } from './routes/memos/index'
import { Route as MemosCreateRouteImport } from './routes/memos/create'
import { Route as MemosMemoIdRouteImport } from './routes/memos/$memoId'
import { Route as BooksGamesRouteImport } from './routes/books/games'
import { Route as BooksCountriesRouteImport } from './routes/books/countries'
import { Route as BooksConferencesRouteImport } from './routes/books/conferences'
import { Route as ApiYoutubeIndexRouteImport } from './routes/api/youtube/index'
import { Route as ApiTodosIndexRouteImport } from './routes/api/todos/index'
import { Route as ApiMemosIndexRouteImport } from './routes/api/memos/index'
import { Route as ApiGamesIndexRouteImport } from './routes/api/games/index'
import { Route as ApiCountriesIndexRouteImport } from './routes/api/countries/index'
import { Route as ApiConferencesIndexRouteImport } from './routes/api/conferences/index'
import { Route as ApiTodosTodoIdRouteImport } from './routes/api/todos/$todoId'
import { Route as ApiMemosMemoIdRouteImport } from './routes/api/memos/$memoId'
import { Route as ApiGamesGameIdRouteImport } from './routes/api/games/$gameId'
import { Route as ApiCountriesCountryIdRouteImport } from './routes/api/countries/$countryId'
import { Route as ApiConferencesConferenceIdRouteImport } from './routes/api/conferences/$conferenceId'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authedRoute = _authedRouteImport.update({
  id: '/__authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosIndexRoute = MemosIndexRouteImport.update({
  id: '/memos/',
  path: '/memos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosCreateRoute = MemosCreateRouteImport.update({
  id: '/memos/create',
  path: '/memos/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosMemoIdRoute = MemosMemoIdRouteImport.update({
  id: '/memos/$memoId',
  path: '/memos/$memoId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksGamesRoute = BooksGamesRouteImport.update({
  id: '/books/games',
  path: '/books/games',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksCountriesRoute = BooksCountriesRouteImport.update({
  id: '/books/countries',
  path: '/books/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksConferencesRoute = BooksConferencesRouteImport.update({
  id: '/books/conferences',
  path: '/books/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeIndexRoute = ApiYoutubeIndexRouteImport.update({
  id: '/api/youtube/',
  path: '/api/youtube/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosIndexRoute = ApiTodosIndexRouteImport.update({
  id: '/api/todos/',
  path: '/api/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemosIndexRoute = ApiMemosIndexRouteImport.update({
  id: '/api/memos/',
  path: '/api/memos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIndexRoute = ApiGamesIndexRouteImport.update({
  id: '/api/games/',
  path: '/api/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesIndexRoute = ApiCountriesIndexRouteImport.update({
  id: '/api/countries/',
  path: '/api/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConferencesIndexRoute = ApiConferencesIndexRouteImport.update({
  id: '/api/conferences/',
  path: '/api/conferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosTodoIdRoute = ApiTodosTodoIdRouteImport.update({
  id: '/api/todos/$todoId',
  path: '/api/todos/$todoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemosMemoIdRoute = ApiMemosMemoIdRouteImport.update({
  id: '/api/memos/$memoId',
  path: '/api/memos/$memoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesGameIdRoute = ApiGamesGameIdRouteImport.update({
  id: '/api/games/$gameId',
  path: '/api/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesCountryIdRoute = ApiCountriesCountryIdRouteImport.update({
  id: '/api/countries/$countryId',
  path: '/api/countries/$countryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConferencesConferenceIdRoute =
  ApiConferencesConferenceIdRouteImport.update({
    id: '/api/conferences/$conferenceId',
    path: '/api/conferences/$conferenceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/matches': typeof MatchesRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/youtube': typeof YoutubeRoute
  '/books/conferences': typeof BooksConferencesRoute
  '/books/countries': typeof BooksCountriesRoute
  '/books/games': typeof BooksGamesRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/memos/create': typeof MemosCreateRoute
  '/memos': typeof MemosIndexRoute
  '/api/conferences/$conferenceId': typeof ApiConferencesConferenceIdRoute
  '/api/countries/$countryId': typeof ApiCountriesCountryIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRoute
  '/api/memos/$memoId': typeof ApiMemosMemoIdRoute
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/api/conferences': typeof ApiConferencesIndexRoute
  '/api/countries': typeof ApiCountriesIndexRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/api/memos': typeof ApiMemosIndexRoute
  '/api/todos': typeof ApiTodosIndexRoute
  '/api/youtube': typeof ApiYoutubeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/matches': typeof MatchesRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/youtube': typeof YoutubeRoute
  '/books/conferences': typeof BooksConferencesRoute
  '/books/countries': typeof BooksCountriesRoute
  '/books/games': typeof BooksGamesRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/memos/create': typeof MemosCreateRoute
  '/memos': typeof MemosIndexRoute
  '/api/conferences/$conferenceId': typeof ApiConferencesConferenceIdRoute
  '/api/countries/$countryId': typeof ApiCountriesCountryIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRoute
  '/api/memos/$memoId': typeof ApiMemosMemoIdRoute
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/api/conferences': typeof ApiConferencesIndexRoute
  '/api/countries': typeof ApiCountriesIndexRoute
  '/api/games': typeof ApiGamesIndexRoute
  '/api/memos': typeof ApiMemosIndexRoute
  '/api/todos': typeof ApiTodosIndexRoute
  '/api/youtube': typeof ApiYoutubeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authed': typeof _authedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/matches': typeof MatchesRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/youtube': typeof YoutubeRoute
  '/books/conferences': typeof BooksConferencesRoute
  '/books/countries': typeof BooksCountriesRoute
  '/books/games': typeof BooksGamesRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/memos/create': typeof MemosCreateRoute
  '/memos/': typeof MemosIndexRoute
  '/api/conferences/$conferenceId': typeof ApiConferencesConferenceIdRoute
  '/api/countries/$countryId': typeof ApiCountriesCountryIdRoute
  '/api/games/$gameId': typeof ApiGamesGameIdRoute
  '/api/memos/$memoId': typeof ApiMemosMemoIdRoute
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/api/conferences/': typeof ApiConferencesIndexRoute
  '/api/countries/': typeof ApiCountriesIndexRoute
  '/api/games/': typeof ApiGamesIndexRoute
  '/api/memos/': typeof ApiMemosIndexRoute
  '/api/todos/': typeof ApiTodosIndexRoute
  '/api/youtube/': typeof ApiYoutubeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/matches'
    | '/signup'
    | '/upload'
    | '/youtube'
    | '/books/conferences'
    | '/books/countries'
    | '/books/games'
    | '/memos/$memoId'
    | '/memos/create'
    | '/memos'
    | '/api/conferences/$conferenceId'
    | '/api/countries/$countryId'
    | '/api/games/$gameId'
    | '/api/memos/$memoId'
    | '/api/todos/$todoId'
    | '/api/conferences'
    | '/api/countries'
    | '/api/games'
    | '/api/memos'
    | '/api/todos'
    | '/api/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/matches'
    | '/signup'
    | '/upload'
    | '/youtube'
    | '/books/conferences'
    | '/books/countries'
    | '/books/games'
    | '/memos/$memoId'
    | '/memos/create'
    | '/memos'
    | '/api/conferences/$conferenceId'
    | '/api/countries/$countryId'
    | '/api/games/$gameId'
    | '/api/memos/$memoId'
    | '/api/todos/$todoId'
    | '/api/conferences'
    | '/api/countries'
    | '/api/games'
    | '/api/memos'
    | '/api/todos'
    | '/api/youtube'
  id:
    | '__root__'
    | '/'
    | '/__authed'
    | '/login'
    | '/logout'
    | '/matches'
    | '/signup'
    | '/upload'
    | '/youtube'
    | '/books/conferences'
    | '/books/countries'
    | '/books/games'
    | '/memos/$memoId'
    | '/memos/create'
    | '/memos/'
    | '/api/conferences/$conferenceId'
    | '/api/countries/$countryId'
    | '/api/games/$gameId'
    | '/api/memos/$memoId'
    | '/api/todos/$todoId'
    | '/api/conferences/'
    | '/api/countries/'
    | '/api/games/'
    | '/api/memos/'
    | '/api/todos/'
    | '/api/youtube/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authedRoute: typeof _authedRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MatchesRoute: typeof MatchesRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
  YoutubeRoute: typeof YoutubeRoute
  BooksConferencesRoute: typeof BooksConferencesRoute
  BooksCountriesRoute: typeof BooksCountriesRoute
  BooksGamesRoute: typeof BooksGamesRoute
  MemosMemoIdRoute: typeof MemosMemoIdRoute
  MemosCreateRoute: typeof MemosCreateRoute
  MemosIndexRoute: typeof MemosIndexRoute
  ApiConferencesConferenceIdRoute: typeof ApiConferencesConferenceIdRoute
  ApiCountriesCountryIdRoute: typeof ApiCountriesCountryIdRoute
  ApiGamesGameIdRoute: typeof ApiGamesGameIdRoute
  ApiMemosMemoIdRoute: typeof ApiMemosMemoIdRoute
  ApiTodosTodoIdRoute: typeof ApiTodosTodoIdRoute
  ApiConferencesIndexRoute: typeof ApiConferencesIndexRoute
  ApiCountriesIndexRoute: typeof ApiCountriesIndexRoute
  ApiGamesIndexRoute: typeof ApiGamesIndexRoute
  ApiMemosIndexRoute: typeof ApiMemosIndexRoute
  ApiTodosIndexRoute: typeof ApiTodosIndexRoute
  ApiYoutubeIndexRoute: typeof ApiYoutubeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authed': {
      id: '/__authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/': {
      id: '/memos/'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/create': {
      id: '/memos/create'
      path: '/memos/create'
      fullPath: '/memos/create'
      preLoaderRoute: typeof MemosCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/$memoId': {
      id: '/memos/$memoId'
      path: '/memos/$memoId'
      fullPath: '/memos/$memoId'
      preLoaderRoute: typeof MemosMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/games': {
      id: '/books/games'
      path: '/books/games'
      fullPath: '/books/games'
      preLoaderRoute: typeof BooksGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/countries': {
      id: '/books/countries'
      path: '/books/countries'
      fullPath: '/books/countries'
      preLoaderRoute: typeof BooksCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/conferences': {
      id: '/books/conferences'
      path: '/books/conferences'
      fullPath: '/books/conferences'
      preLoaderRoute: typeof BooksConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/': {
      id: '/api/youtube/'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos/': {
      id: '/api/todos/'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memos/': {
      id: '/api/memos/'
      path: '/api/memos'
      fullPath: '/api/memos'
      preLoaderRoute: typeof ApiMemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/': {
      id: '/api/games/'
      path: '/api/games'
      fullPath: '/api/games'
      preLoaderRoute: typeof ApiGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries/': {
      id: '/api/countries/'
      path: '/api/countries'
      fullPath: '/api/countries'
      preLoaderRoute: typeof ApiCountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conferences/': {
      id: '/api/conferences/'
      path: '/api/conferences'
      fullPath: '/api/conferences'
      preLoaderRoute: typeof ApiConferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos/$todoId': {
      id: '/api/todos/$todoId'
      path: '/api/todos/$todoId'
      fullPath: '/api/todos/$todoId'
      preLoaderRoute: typeof ApiTodosTodoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memos/$memoId': {
      id: '/api/memos/$memoId'
      path: '/api/memos/$memoId'
      fullPath: '/api/memos/$memoId'
      preLoaderRoute: typeof ApiMemosMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId': {
      id: '/api/games/$gameId'
      path: '/api/games/$gameId'
      fullPath: '/api/games/$gameId'
      preLoaderRoute: typeof ApiGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries/$countryId': {
      id: '/api/countries/$countryId'
      path: '/api/countries/$countryId'
      fullPath: '/api/countries/$countryId'
      preLoaderRoute: typeof ApiCountriesCountryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conferences/$conferenceId': {
      id: '/api/conferences/$conferenceId'
      path: '/api/conferences/$conferenceId'
      fullPath: '/api/conferences/$conferenceId'
      preLoaderRoute: typeof ApiConferencesConferenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authedRoute: _authedRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MatchesRoute: MatchesRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
  YoutubeRoute: YoutubeRoute,
  BooksConferencesRoute: BooksConferencesRoute,
  BooksCountriesRoute: BooksCountriesRoute,
  BooksGamesRoute: BooksGamesRoute,
  MemosMemoIdRoute: MemosMemoIdRoute,
  MemosCreateRoute: MemosCreateRoute,
  MemosIndexRoute: MemosIndexRoute,
  ApiConferencesConferenceIdRoute: ApiConferencesConferenceIdRoute,
  ApiCountriesCountryIdRoute: ApiCountriesCountryIdRoute,
  ApiGamesGameIdRoute: ApiGamesGameIdRoute,
  ApiMemosMemoIdRoute: ApiMemosMemoIdRoute,
  ApiTodosTodoIdRoute: ApiTodosTodoIdRoute,
  ApiConferencesIndexRoute: ApiConferencesIndexRoute,
  ApiCountriesIndexRoute: ApiCountriesIndexRoute,
  ApiGamesIndexRoute: ApiGamesIndexRoute,
  ApiMemosIndexRoute: ApiMemosIndexRoute,
  ApiTodosIndexRoute: ApiTodosIndexRoute,
  ApiYoutubeIndexRoute: ApiYoutubeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
